/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlinemanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author divya
 */
public class Passengers extends javax.swing.JFrame {

    public Passengers() {
        initComponents();
        DisplayPassengers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        PassengerName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PNameTb = new javax.swing.JTextField();
        NatCb = new javax.swing.JComboBox<>();
        GenCb = new javax.swing.JComboBox<>();
        PassNumTb = new javax.swing.JTextField();
        PPhoneTb = new javax.swing.JTextField();
        PAddressTb = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PassengersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(29, 72, 134));

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        jLabel3.setFont(new java.awt.Font("Artifakt Element Book", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 72, 134));
        jLabel3.setText("Falcon Airlines");

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(29, 72, 134));
        jLabel4.setText("x");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(29, 72, 134));

        jPanel4.setBackground(new java.awt.Color(29, 72, 134));

        jPanel5.setBackground(new java.awt.Color(29, 72, 134));

        jPanel6.setBackground(new java.awt.Color(29, 72, 134));

        PassengerName.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        PassengerName.setForeground(new java.awt.Color(252, 177, 48));
        PassengerName.setText("Passenger Name");

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(252, 177, 48));
        jLabel8.setText("Nationality");

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(252, 177, 48));
        jLabel9.setText("Gender");

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(252, 177, 48));
        jLabel10.setText("Passport Number");

        jLabel11.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(252, 177, 48));
        jLabel11.setText("Phone Number");

        jLabel12.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(252, 177, 48));
        jLabel12.setText("Address");

        jLabel13.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(252, 177, 48));
        jLabel13.setText("Passenger Details");

        PNameTb.setBackground(new java.awt.Color(29, 72, 134));
        PNameTb.setForeground(new java.awt.Color(252, 177, 48));
        PNameTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));

        NatCb.setBackground(new java.awt.Color(29, 72, 134));
        NatCb.setForeground(new java.awt.Color(252, 177, 48));
        NatCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));
        NatCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India", "USA", "UK", "Canada", "Australia", "Germany", "France", "Japan", "China", "Brazil" }));

        GenCb.setBackground(new java.awt.Color(29, 72, 134));
        GenCb.setForeground(new java.awt.Color(252, 177, 48));
        GenCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));
        GenCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        PassNumTb.setBackground(new java.awt.Color(29, 72, 134));
        PassNumTb.setForeground(new java.awt.Color(252, 177, 48));
        PassNumTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));

        PPhoneTb.setBackground(new java.awt.Color(29, 72, 134));
        PPhoneTb.setForeground(new java.awt.Color(252, 177, 48));
        PPhoneTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));

        PAddressTb.setBackground(new java.awt.Color(29, 72, 134));
        PAddressTb.setForeground(new java.awt.Color(252, 177, 48));
        PAddressTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));

        SaveBtn.setBackground(new java.awt.Color(29, 72, 134));
        SaveBtn.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        SaveBtn.setForeground(new java.awt.Color(252, 177, 48));
        SaveBtn.setText("Save");
        SaveBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));
        SaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBtnMouseClicked(evt);
            }
        });
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        EditBtn.setBackground(new java.awt.Color(29, 72, 134));
        EditBtn.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        EditBtn.setForeground(new java.awt.Color(252, 177, 48));
        EditBtn.setText("Edit");
        EditBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
        });
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(29, 72, 134));
        DeleteBtn.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(252, 177, 48));
        DeleteBtn.setText("Delete");
        DeleteBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        BackBtn.setBackground(new java.awt.Color(29, 72, 134));
        BackBtn.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(252, 177, 48));
        BackBtn.setText("Back");
        BackBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        PassengersTable.setBackground(new java.awt.Color(29, 72, 134));
        PassengersTable.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        PassengersTable.setForeground(new java.awt.Color(252, 177, 48));
        PassengersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Passenger ID", "Name", "Nationality", "Gender", "Passport", "Phone", "Address"
            }
        ));
        PassengersTable.setGridColor(new java.awt.Color(252, 177, 48));
        PassengersTable.setSelectionBackground(new java.awt.Color(252, 177, 48));
        PassengersTable.setSelectionForeground(new java.awt.Color(29, 72, 134));
        PassengersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassengersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PassengersTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PassengerName)
                                .addGap(18, 18, 18)
                                .addComponent(PNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(NatCb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(GenCb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(PassNumTb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(PPhoneTb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(PAddressTb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(25, 25, 25)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassengerName)
                    .addComponent(PNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(NatCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(GenCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(PassNumTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(PPhoneTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(PAddressTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBtnMouseClicked
        if(PNameTb.getText().isEmpty() || PassNumTb.getText().isEmpty() || PPhoneTb.getText().isEmpty() || PAddressTb.getText().isEmpty() || NatCb.getSelectedIndex()== -1 || GenCb.getSelectedIndex()== -1 ){
            JOptionPane.showMessageDialog(this, "Missing Information");
        }else{
            try {
                Con = DatabaseConfig.getConnection();
                PreparedStatement Add = Con.prepareStatement("insert into PassengerTbl values(?,?,?,?,?,?,?)");
                Add.setInt(1, PassId);
                Add.setString(2, PNameTb.getText());
                Add.setString(3, NatCb.getSelectedItem().toString());
                Add.setString(4, GenCb.getSelectedItem().toString());
                Add.setString(5, PassNumTb.getText());
                Add.setString(6, PPhoneTb.getText());
                Add.setString(7, PAddressTb.getText());
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Passenger Added");
                Con.close();
                DisplayPassengers();
                Clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error adding passenger: " + e.getMessage());
            } finally {
                DatabaseConfig.closeConnection(Con);
            }
        }
    }//GEN-LAST:event_SaveBtnMouseClicked

    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
        if(Key==0){
            JOptionPane.showMessageDialog(this, "Please Select a Passenger");
        }else{
            try{
                Con = DatabaseConfig.getConnection();
                String Query = "Delete from PassengerTbl where PassId="+Key;
                Statement Del = Con.createStatement();
                Del.executeUpdate(Query);
                JOptionPane.showMessageDialog(this, "Passenger Deleted");
                DisplayPassengers();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error deleting passenger: " + e.getMessage());
            } finally {
                DatabaseConfig.closeConnection(Con);
            }
        }
    }//GEN-LAST:event_DeleteBtnMouseClicked

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        new MainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked

    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        if(Key==0){
            JOptionPane.showMessageDialog(this, "Select a Passenger");
        }else{
            try {
                Con = DatabaseConfig.getConnection();
                String Query = "Update PassengerTbl set PassName=?, PassNationality=?, PassGender=?, PassPassport=?, PassPhone=?, PassAddress=? where PassId=?";
                PreparedStatement Add = Con.prepareStatement(Query);
                Add.setString(1, PNameTb.getText());
                Add.setString(2, NatCb.getSelectedItem().toString());
                Add.setString(3, GenCb.getSelectedItem().toString());
                Add.setString(4, PassNumTb.getText());
                Add.setString(5, PPhoneTb.getText());
                Add.setString(6, PAddressTb.getText());
                Add.setInt(7, Key);
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Passenger Updated");
                Con.close();
                DisplayPassengers();
                Clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error updating passenger: " + e.getMessage());
            } finally {
                DatabaseConfig.closeConnection(Con);
            }
        }
    }//GEN-LAST:event_EditBtnMouseClicked

    private void PassNumTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassNumTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassNumTbActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passengers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JComboBox<String> GenCb;
    private javax.swing.JComboBox<String> NatCb;
    private javax.swing.JTextField PAddressTb;
    private javax.swing.JTextField PNameTb;
    private javax.swing.JTextField PPhoneTb;
    private javax.swing.JTextField PassNumTb;
    private javax.swing.JLabel PassengerName;
    private javax.swing.JTable PassengersTable;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null, Rs1=null;
    Statement St = null, St1=null;
    private void DisplayPassengers(){
        try{
            Con = DatabaseConfig.getConnection();
            St = Con.createStatement();
            Rs = St.executeQuery("select * from PassengerTbl");
            
            // Create table model manually since DbUtils is not available
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Passenger ID");
            model.addColumn("Name");
            model.addColumn("Nationality");
            model.addColumn("Gender");
            model.addColumn("Passport");
            model.addColumn("Phone");
            model.addColumn("Address");
            
            while(Rs.next()) {
                model.addRow(new Object[]{
                    Rs.getString("PassId"),
                    Rs.getString("PassName"),
                    Rs.getString("PassNationality"),
                    Rs.getString("PassGender"),
                    Rs.getString("PassPassport"),
                    Rs.getString("PassPhone"),
                    Rs.getString("PassAddress")
                });
            }
            
            PassengersTable.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error displaying passengers: " + e.getMessage());
        } finally {
            DatabaseConfig.closeConnection(Con);
        }
    }
    
    int PassId = 0;
    private void CountPassengers()
    {
        try{
            Con = DatabaseConfig.getConnection();
            St = Con.createStatement();
            Rs = St.executeQuery("select max(PassId) from PassengerTbl");
            while(Rs.next()){
                PassId = Rs.getInt(1);
            }
            PassId = PassId + 1;
        }catch(Exception e){
            PassId = 1;
        } finally {
            DatabaseConfig.closeConnection(Con);
        }
    }
    
    private void Clear(){
        PNameTb.setText("");
        PassNumTb.setText("");
        PPhoneTb.setText("");
        PAddressTb.setText("");
    }
    
    int Key=0;
    private void PassengersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassengersTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) PassengersTable.getModel();
        int MyIndex = PassengersTable.getSelectedRow();
        Key = Integer.valueOf(model.getValueAt(MyIndex, 0).toString());
        PNameTb.setText(model.getValueAt(MyIndex,1).toString());
        NatCb.setSelectedItem(model.getValueAt(MyIndex,2).toString());
        GenCb.setSelectedItem(model.getValueAt(MyIndex,3).toString());
        PassNumTb.setText(model.getValueAt(MyIndex,4).toString());
        PPhoneTb.setText(model.getValueAt(MyIndex,5).toString());
        PAddressTb.setText(model.getValueAt(MyIndex,6).toString());
    }//GEN-LAST:event_PassengersTableMouseClicked
}
