
package airlinemanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author divya
 */
public class TicketBooking extends javax.swing.JFrame {

    public TicketBooking() {
        initComponents();
        GetPassenger();
        GetFlights();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PassIdCb = new javax.swing.JComboBox<>();
        PassNameTb = new javax.swing.JTextField();
        FCodeCb = new javax.swing.JComboBox<>();
        GenTb = new javax.swing.JTextField();
        NationalityTb = new javax.swing.JTextField();
        PassNumTb = new javax.swing.JTextField();
        AmountTb = new javax.swing.JTextField();
        BookBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookingTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(29, 72, 134));

        jPanel5.setBackground(new java.awt.Color(255, 204, 51));

        jLabel3.setFont(new java.awt.Font("Artifakt Element Book", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 72, 134));
        jLabel3.setText("Falcon Airlines");

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(29, 72, 134));
        jLabel6.setText("x");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(252, 177, 48));
        jLabel7.setText("Passenger ID");

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(252, 177, 48));
        jLabel8.setText("Passenger Name");

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(252, 177, 48));
        jLabel9.setText("Flight Code");

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(252, 177, 48));
        jLabel10.setText("Gender");

        jLabel11.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(252, 177, 48));
        jLabel11.setText("Nationality");

        jLabel12.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(252, 177, 48));
        jLabel12.setText("Passport Number");

        jLabel13.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(252, 177, 48));
        jLabel13.setText("Amount");

        jLabel14.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(252, 177, 48));
        jLabel14.setText("Ticket Booking");

        PassIdCb.setBackground(new java.awt.Color(29, 72, 134));
        PassIdCb.setForeground(new java.awt.Color(252, 177, 48));
        PassIdCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));
        PassIdCb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassIdCbMouseClicked(evt);
            }
        });
        PassIdCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassIdCbActionPerformed(evt);
            }
        });

        PassNameTb.setBackground(new java.awt.Color(29, 72, 134));
        PassNameTb.setForeground(new java.awt.Color(252, 177, 48));
        PassNameTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));

        FCodeCb.setBackground(new java.awt.Color(29, 72, 134));
        FCodeCb.setForeground(new java.awt.Color(252, 177, 48));
        FCodeCb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));
        FCodeCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCodeCbActionPerformed(evt);
            }
        });

        GenTb.setBackground(new java.awt.Color(29, 72, 134));
        GenTb.setForeground(new java.awt.Color(252, 177, 48));
        GenTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));

        NationalityTb.setBackground(new java.awt.Color(29, 72, 134));
        NationalityTb.setForeground(new java.awt.Color(252, 177, 48));
        NationalityTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));

        PassNumTb.setBackground(new java.awt.Color(29, 72, 134));
        PassNumTb.setForeground(new java.awt.Color(252, 177, 48));
        PassNumTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));

        AmountTb.setBackground(new java.awt.Color(29, 72, 134));
        AmountTb.setForeground(new java.awt.Color(252, 177, 48));
        AmountTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));

        BookBtn.setBackground(new java.awt.Color(29, 72, 134));
        BookBtn.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        BookBtn.setForeground(new java.awt.Color(252, 177, 48));
        BookBtn.setText("Book");
        BookBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));
        BookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookBtnMouseClicked(evt);
            }
        });
        BookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookBtnActionPerformed(evt);
            }
        });

        ResetBtn.setBackground(new java.awt.Color(29, 72, 134));
        ResetBtn.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        ResetBtn.setForeground(new java.awt.Color(252, 177, 48));
        ResetBtn.setText("Reset");
        ResetBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));
        ResetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetBtnMouseClicked(evt);
            }
        });
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        BackBtn.setBackground(new java.awt.Color(29, 72, 134));
        BackBtn.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(252, 177, 48));
        BackBtn.setText("Back");
        BackBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)));
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        BookingTable.setBackground(new java.awt.Color(29, 72, 134));
        BookingTable.setFont(new java.awt.Font("Corbel", 1, 12)); // NOI18N
        BookingTable.setForeground(new java.awt.Color(252, 177, 48));
        BookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Passenger ID", "Passenger Name", "Flight Code", "Gender", "Passport", "Nationality", "Amount", "Date"
            }
        ));
        BookingTable.setGridColor(new java.awt.Color(252, 177, 48));
        BookingTable.setSelectionBackground(new java.awt.Color(252, 177, 48));
        BookingTable.setSelectionForeground(new java.awt.Color(29, 72, 134));
        BookingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BookingTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(PassIdCb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(PassNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(FCodeCb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(GenTb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(NationalityTb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(PassNumTb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(AmountTb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(BookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(25, 25, 25)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PassIdCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(PassNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(FCodeCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(GenTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(NationalityTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(PassNumTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(AmountTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void BookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookBtnActionPerformed

    private void PassNameTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassNameTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassNameTbActionPerformed

    private void NationalityTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationalityTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NationalityTbActionPerformed

    private void BookingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingTableMouseClicked

    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null, Rs1=null;
    Statement St = null, St1=null;
    private void GetPassenger()
    {
        try{
            Con = DatabaseConfig.getConnection();
            St = Con.createStatement();
            Rs = St.executeQuery("select * from PassengerTbl");
            while(Rs.next()){
                PassIdCb.addItem(Rs.getString("PassId"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error loading passengers: " + e.getMessage());
        } finally {
            DatabaseConfig.closeConnection(Con);
        }
    }
    
    private void GetFlights()
    {
        try{
            Con = DatabaseConfig.getConnection();
            St = Con.createStatement();
            Rs = St.executeQuery("select * from FlightTbl");
            while(Rs.next()){
                FCodeCb.addItem(Rs.getString("FlCode"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error loading flights: " + e.getMessage());
        } finally {
            DatabaseConfig.closeConnection(Con);
        }
    }
    
    private void GetPassengerData()
    {
        try{
            Con = DatabaseConfig.getConnection();
            St = Con.createStatement();
            Rs = St.executeQuery("select * from PassengerTbl where PassId="+PassIdCb.getSelectedItem());
            while(Rs.next()){
                PassNameTb.setText(Rs.getString("PassName"));
                GenTb.setText(Rs.getString("PassGender"));
                NationalityTb.setText(Rs.getString("PassNationality"));
                PassNumTb.setText(Rs.getString("PassPassport"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error loading passenger data: " + e.getMessage());
        } finally {
            DatabaseConfig.closeConnection(Con);
        }
    }
    
    private void DisplayBooking(){
        try{
            Con = DatabaseConfig.getConnection();
            St = Con.createStatement();
            Rs = St.executeQuery("select * from BookingTbl");
            
            // Create table model manually since DbUtils is not available
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Booking ID");
            model.addColumn("Passenger ID");
            model.addColumn("Passenger Name");
            model.addColumn("Flight Code");
            model.addColumn("Gender");
            model.addColumn("Passport");
            model.addColumn("Nationality");
            model.addColumn("Amount");
            model.addColumn("Date");
            
            while(Rs.next()) {
                model.addRow(new Object[]{
                    Rs.getString("BookId"),
                    Rs.getString("BookPassId"),
                    Rs.getString("BookPassName"),
                    Rs.getString("BookFlightCode"),
                    Rs.getString("BookGender"),
                    Rs.getString("BookPassport"),
                    Rs.getString("BookNationality"),
                    Rs.getString("BookAmount"),
                    Rs.getString("BookDate")
                });
            }
            
            BookingTable.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error displaying bookings: " + e.getMessage());
        } finally {
            DatabaseConfig.closeConnection(Con);
        }
    }
    
    int TId = 0;
    private void CountFlights()
    {
        try{
            Con = DatabaseConfig.getConnection();
            St = Con.createStatement();
            Rs = St.executeQuery("select max(BookId) from BookingTbl");
            while(Rs.next()){
                TId = Rs.getInt(1);
            }
            TId = TId + 1;
        }catch(Exception e){
            TId = 1;
        } finally {
            DatabaseConfig.closeConnection(Con);
        }
    }
    
    private void BookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookBtnMouseClicked
        if(PassIdCb.getSelectedIndex()== -1 || FCodeCb.getSelectedIndex()== -1 || AmountTb.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information");
        }else{
            try {
                CountFlights();
                Con = DatabaseConfig.getConnection();
                PreparedStatement Add = Con.prepareStatement("insert into BookingTbl values(?,?,?,?,?,?,?,?,?)");
                Add.setInt(1, TId);
                Add.setInt(2, Integer.valueOf(PassIdCb.getSelectedItem().toString()));
                Add.setString(3, PassNameTb.getText());
                Add.setString(4, FCodeCb.getSelectedItem().toString());
                Add.setString(5, GenTb.getText());
                Add.setString(6, PassNumTb.getText());
                Add.setString(7, NationalityTb.getText());
                Add.setString(8, AmountTb.getText());
                Add.setString(9, java.time.LocalDate.now().toString());
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Ticket Booked");
                Con.close();
                DisplayBooking();
                Clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error booking ticket: " + e.getMessage());
            } finally {
                DatabaseConfig.closeConnection(Con);
            }
        }
    }//GEN-LAST:event_BookBtnMouseClicked

    private void PassIdCbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassIdCbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PassIdCbMouseClicked

    private void PassIdCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassIdCbActionPerformed
        GetPassengerData();
    }//GEN-LAST:event_PassIdCbActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        new MainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked

    private void Clear(){
        PassNameTb.setText("");
        GenTb.setText("");
        NationalityTb.setText("");
        PassNumTb.setText("");
        AmountTb.setText("");
    }
    
    private void ResetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetBtnMouseClicked
        Clear();
    }//GEN-LAST:event_ResetBtnMouseClicked

    private void FCodeCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCodeCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FCodeCbActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountTb;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BookBtn;
    private javax.swing.JTable BookingTable;
    private javax.swing.JComboBox<String> FCodeCb;
    private javax.swing.JTextField GenTb;
    private javax.swing.JTextField NationalityTb;
    private javax.swing.JComboBox<String> PassIdCb;
    private javax.swing.JTextField PassNameTb;
    private javax.swing.JTextField PassNumTb;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
